// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdAY0btx2wzn07dSKa_kjVy-dvKDMeDI',
    appId: '1:848498097413:web:53b3aba51ee403f389cb6c',
    messagingSenderId: '848498097413',
    projectId: 'hotcard-ff104',
    authDomain: 'hotcard-ff104.firebaseapp.com',
    storageBucket: 'hotcard-ff104.appspot.com',
    measurementId: 'G-YDD1EKE89V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0bgnFXM3csHmosPaedB-gCHPKHNeMwEI',
    appId: '1:848498097413:android:62f111323ff0342889cb6c',
    messagingSenderId: '848498097413',
    projectId: 'hotcard-ff104',
    storageBucket: 'hotcard-ff104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QelP8A3v7SXB4e5xMcAZvhZGcxz2O_g',
    appId: '1:848498097413:ios:2b51952757e65dd989cb6c',
    messagingSenderId: '848498097413',
    projectId: 'hotcard-ff104',
    storageBucket: 'hotcard-ff104.appspot.com',
    androidClientId: '848498097413-kovpor3vfu7akukd1m6na7bubs8do1fj.apps.googleusercontent.com',
    iosClientId: '848498097413-dgrku7q31l3k0fpu2ss21f8uq5agg9j1.apps.googleusercontent.com',
    iosBundleId: 'com.tapp.hotcard',
  );
}
